- name: Demo on vars
  hosts: localhost
  vars:
    URL_PLAY: play.example.com
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: URL_PLAY - {{ URL_PLAY }}
    - name: Task variable
      ansible.builtin.debug:
        msg: URL_TASK - {{ URL_TASK }}
      vars:
        URL_TASK: tasks.example.com
#
#    # Store result of a task, to OUTPUT variable
#    - name: demo
#      ansible.builtin.shell: uptime
#      register: OUTPUT
#
#    # Retrive the OUTPUT variable
#    - name: Print OUTPUT of previous task
#      ansible.builtin.debug:
#        msg: "{{ OUTPUT }}"
#
#    # Retrive the OUTPUT variable using JSON query
#    - name: Print OUTPUT of previous task with only output of shell command
#      ansible.builtin.debug:
#        msg: "{{ OUTPUT.stdout }}"
#
#
  roles:
    - demo

